# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21
  pre_build:
    commands:
      # export the env variables
      - echo AUTH=${AUTH} >> .env
  build:
    commands:
      - echo Run.
      - npm install
      - npm run book
