steps:
  - name: 'node'
    entrypoint: 'npm'
    args: [ 'install' ]
  - name: 'node'
    entrypoint: 'npm'
    args: [ 'run','book' ]
    secretEnv: [ 'AUTH' ]
    availableSecrets:
      secretManager:
        - versionName: projects/575043940322/secrets/AUTH
          env: 'AUTH'