name: Book class
on:
  schedule:
    - cron: '0 8 * * 3'  # Runs at 19:00 on Fridays (0 minute, 20 hour, any day of month, any month, wednesday (3))
    - cron: '0 9 * * 3'  # Runs at 19:00 on Fridays (0 minute, 20 hour, any day of month, any month, Friday (5))
  push:
    branches:
      - "test-workflow"


jobs:
  book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run book
        env:
          AUTH: ${{ secrets.AUTH }}
          name: 'edu'
      
