name: Book class
on:
  schedule:
    - cron: '30 18 * * 3,5'  # Runs at 19:00 UTC on wednesday (0 minute, 20 hour, any day of month, any month, wednesday (3) and Friday (5))


jobs:
  book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: |
          dt=$(date '+%d/%m/%Y %H:%M:%S');\
          echo "$dt"
      - run: npm ci
      - run: npm run book
        env:
          AUTH: ${{ secrets.AUTH }}
      
