name: Book class
on:
  schedule:
#    - cron: '0 21 * * 3,5'  # Runs at 20:00 on wednesday (0 minute, 20 hour, any day of month, any month, wednesday (3))
    - cron: '*/5 * * * *'


jobs:
  book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run book
        env:
          AUTH: ${{ secrets.AUTH }}
      
